# Generated by Django 3.0.5 on 2023-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSDAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSDMODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Characteristic', models.IntegerField()),
                ('GDP_in_billion', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
